# Use the official PostgreSQL image as a base
FROM postgres:latest

# Install vim
RUN apt-get update && apt-get install -y vim

# Any other customization or setup can go here

# Continue with the CMD from the base image entrypoint
CMD ["postgres"]
